### ISSUE TITLE
Unable to run on real ios device or build ios --release

### ISSUE THREAD

**Issue by hyqshr** [lyledean1/flutter_whisper.cpp#15]
It run successfully on ios simulator, but can not run on my ios device (Iphone 14 Pro) or run flutter build ios --release
tested on Xcode 15.0, Flutter 3.13.4, ios 17

![image](https://github.com/lyledean1/flutter_whisper.cpp/assets/63976795/1d09b376-2ae4-4f76-980d-fe3d830ede10)

Running Xcode build...                                                  
Xcode build done.                                            8.2s
Failed to build iOS app
Error (Xcode): could not compile `cfg-if` (lib) due to 2 previous errors

Error (Xcode): cannot find attribute `derive` in this scope

Error (Xcode): could not compile `libc` (lib) due to 200 previous errors

Encountered error while building for device.

**Comment by hyqshr** [comment]
Solved after correctly config flutter run bridge

[iOS setup](https://web.archive.org/web/20230408050003/https://cjycode.com/flutter_rust_bridge/template/setup_ios.html#ios-setup)
iOS requires some additional Rust targets for cross-compilation:

# 64 bit targets (real device & simulator):
rustup target add aarch64-apple-ios x86_64-apple-ios
# New simulator target for Xcode 12 and later
rustup target add aarch64-apple-ios-sim

**Comment by lyledean1** [comment]
Nice to hear that you solved this @hyqshr . I think these are covered in the set up for Flutter Rust Bridge but I'll add a link to the setup in the Readme
