### ISSUE TITLE
Doesn't transcribe when build for App Store / TestFlight 

### ISSUE THREAD

**Issue by kaveshan1** [lyledean1/flutter_whisper.cpp#17]
Firstly, thanks for building this epic library! It has worked super well in debug / release build modes, on an iPhone 15 Pro. However when I run the app from App Store / TestFlight, the transcribe feature doesn't work. It seems to record audio fine but doesn't deploy the model.

Anyone else with similar issues / have a fix for this?

**Comment by kaveshan1** [comment]
This seems to be the issue: 
Exception: Subclasses of FlutterRustBridgeBase should be singletons - there should not be two instances (runtimeType=RsWhisperGptPlatform)

**Comment by lyledean1** [comment]
Seems like a similar issue here https://github.com/fzyzcjy/flutter_rust_bridge/issues/1412 as we use the Flutter Rust Bridge in this repo

Seems like you need to strip the iOS symbols https://docs.flutter.dev/platform-integration/ios/c-interop#stripping-ios-symbols

**Comment by kaveshan1** [comment]
Thank you so much for responding so quickly! It worked
